site_name: redast
site_description: Remote Data Storage
site_url: https://rilshok.github.io/redast
repo_url: https://github.com/rilshok/redast
repo_name: "rilshok/redast"
watch: [redast]

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- toc:
    permalink: "¤"

plugins:
- search
- autorefs
- coverage
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          docstring_style: google
        rendering:
          merge_init_into_class:  true
          show_if_no_docstring: true
          show_bases: false
          show_signature_annotations: true
          show_root_heading: true
          show_source: false

theme:
  name: material
  features:
  - content.code.annotate
  # - navigation.tabs
  # - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

nav:
- Home:
  - index.md
  - Supported storage methods:
    - 01-supported-storage-methods/00-index.md
    - 01-supported-storage-methods/01-local-storage-methods.md
    - 01-supported-storage-methods/02-cloud-storage-methods.md
  - Data storage interface:
    - 02-data-storage-interface/00-index.md
  - Data packaging:
    - 03-data-packaging/00-index.md
- Explanation:
  - 10-explanation.md
- Reference:
  - 20-reference.md


extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
